export enum NotificationStatus {
  SCHEDULED = 'SCHEDULED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
  SENT = 'SENT',
  FAILED_BUSINESS = 'FAILED_BUSINESS',
  FAILED_PERMANENT = 'FAILED_PERMANENT',
}
